services:
  portainer:
     image: portainer/portainer-ce

  catalogdb:
    image: mongo:latest
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=catalogdb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - catalogdb

  basketdb:
    image: redis:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile  

  discountdb:
    image: postgres
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  pgadmin:
    image: dpage/pgadmin4    

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  order_data:
  portainer_data:
  pgadmin_data:

