services:
  catalogdb:
    image: mongo:latest
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=catalogdb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - catalogdb

  basketdb:
    image: redis:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  portainer:
     image: portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:
